TenureListener.Tests/E2ETests/Fixtures/TenureFixture.cs
TenureListener.Tests/E2ETests/Stories/AddNewPersonToTenureTests.cs
TenureListener.Tests/Gateway/TenureInfoGatewayTests.cs
TenureListener/Domain/TenuredAsset.cs

https://hackney.atlassian.net/browse/MTTL-884
Made the TenuredAsset Type property nullable

Made the TenuredAsset.Type nullable

---

TenureListener.Tests/E2ETests/Fixtures/TenureFixture.cs
TenureListener.Tests/E2ETests/Stories/AddNewPersonToTenureTests.cs
TenureListener.Tests/Gateway/TenureInfoGatewayTests.cs
TenureListener.Tests/UseCase/AddNewPersonToTenureTests.cs
TenureListener/Domain/Person/PersonResponseObject.cs
TenureListener/Domain/TenuredAsset.cs
terraform/development/main.tf
terraform/production/main.tf
terraform/staging/main.tf

https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?selectedIssue=MTTL-861
Release changes, including encrypting SQS queues with CMKs, to staging.

Release latest changes to staging

---

TenureListener.Tests/Domain/TenureHelpersTests.cs
TenureListener.Tests/E2ETests/Fixtures/TenureFixture.cs
TenureListener.Tests/Factories/EntityFactoryTest.cs
TenureListener/Domain/TenureHelpers.cs
TenureListener/Domain/TenureInformation.cs
TenureListener/Factories/EntityFactory.cs
TenureListener/Infrastructure/TenureInformationDb.cs

https://hackney.atlassian.net/browse/MTTL-1120
Corrects the calculation and (non) storage of the tenure IsActive flag

Correct tenure IsActive use

---

TenureListener.Tests/Domain/TenureHelpersTests.cs
TenureListener.Tests/E2ETests/Fixtures/TenureFixture.cs
TenureListener.Tests/Factories/EntityFactoryTest.cs
TenureListener/Domain/TenureHelpers.cs
TenureListener/Domain/TenureInformation.cs
TenureListener/Factories/EntityFactory.cs
TenureListener/Infrastructure/TenureInformationDb.cs

Push tenure IsActive fixes to Staging/Production

Release mttl 1120

---

CODEOWNERS

MMH team added as code owners

---

CODEOWNERS
TenureListener/Boundary/User.cs

Release logging changes to staging

Release mttl 1101

---

TenureListener.Tests/Domain/TenureInformationTests.cs
TenureListener.Tests/Gateway/TenureInfoGatewayTests.cs
TenureListener/Domain/TenureInformation.cs
TenureListener/Infrastructure/TenureInformationDb.cs

https://hackney.atlassian.net/browse/MTTL-1264.

Made EndOfTenureDate nullable

---

TenureListener.Tests/Domain/TenureInformationTests.cs
TenureListener.Tests/Gateway/TenureInfoGatewayTests.cs
TenureListener/Domain/TenureInformation.cs
TenureListener/Infrastructure/TenureInformationDb.cs

https://hackney.atlassian.net/browse/MTTL-1264

Release mttl 1264

---

TenureListener/TenureListener.csproj

https://hackney.atlassian.net/browse/MTTL-1252

Use individual Hackney.Core nuget packages

---

terraform/development/main.tf
terraform/development/variables.tf

https://hackney.atlassian.net/browse/MTTL-1461
Get Listener metrics into a Cloudwatch Dashboard
Added Listener CW dashboard

added CW dashboard

---

terraform/production/main.tf
terraform/production/variables.tf
terraform/staging/main.tf
terraform/staging/variable.tf

https://hackney.atlassian.net/browse/MTTL-1461 
Get metrics in a easy to view dashboard
Added Cloudwatch dashboard with widgets for metrics

added staging and prod TF configs for dashboards

---

terraform/development/main.tf
terraform/development/variables.tf
terraform/production/main.tf
terraform/production/variables.tf
terraform/staging/main.tf
terraform/staging/variable.tf

https://hackney.atlassian.net/browse/MTTL-1461
Get metrics in easy to view dashboard
Added Cloudwatch dashboard.

added TF configs for cloudwatch dashboards

---

.circleci/config.yml

We want to deploy to dev from al feature branches to keep Master in a working state 
Removed filter to deploy to development 

removed filter to deploy to dev

---

TenureListener.Tests/E2ETests/Fixtures/PersonApiFixture.cs
TenureListener.Tests/E2ETests/Fixtures/TenureFixture.cs
TenureListener.Tests/E2ETests/Steps/AddNewPersonToTenureSteps.cs
TenureListener.Tests/E2ETests/Stories/AddNewPersonToTenureTests.cs
TenureListener.Tests/Factories/UseCaseFactoryTests.cs
TenureListener.Tests/TenureListener.Tests.csproj
TenureListener/EventVersions.cs
TenureListener/Factories/UseCaseFactory.cs
TenureListener/SqsFunction.cs

https://hackney.atlassian.net/browse/MTTL-1332
Ignore PersonCreatedEvent if it's V2

Ignore PersonCreatedEvent if it's V2

---

.circleci/config.yml
CODEOWNERS
TenureListener.Tests/E2ETests/Fixtures/PersonApiFixture.cs
TenureListener.Tests/E2ETests/Fixtures/TenureFixture.cs
TenureListener.Tests/E2ETests/Steps/AddNewPersonToTenureSteps.cs
TenureListener.Tests/E2ETests/Stories/AddNewPersonToTenureTests.cs
TenureListener.Tests/Factories/UseCaseFactoryTests.cs
TenureListener.Tests/TenureListener.Tests.csproj
TenureListener/EventVersions.cs
TenureListener/Factories/UseCaseFactory.cs
TenureListener/SqsFunction.cs
terraform/development/main.tf
terraform/production/main.tf

Release mttl 1016

---

.circleci/config.yml
TenureListener/Domain/Person/Enums.cs

Add a link to the JIRA ticket that the changes in this PR describe.
Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.
Add descriptions of what changes were made to address the problem and provide a solution.

updating enums

---

TenureListener.Tests/E2ETests/Fixtures/PersonApiFixture.cs
TenureListener.Tests/E2ETests/Steps/AddNewPersonToTenureSteps.cs
TenureListener.Tests/E2ETests/Steps/UpdatePersonDetailsOnTenureSteps.cs
TenureListener.Tests/E2ETests/Stories/AddNewPersonToTenureTests.cs
TenureListener.Tests/E2ETests/Stories/UpdatePersonDetailsOnTenureTests.cs
TenureListener.Tests/Gateway/PersonApiTests.cs
TenureListener.Tests/UseCase/AddNewPersonToTenureTests.cs
TenureListener.Tests/UseCase/UpdatePersonDetailsOnTenureTests.cs
TenureListener/Gateway/Interfaces/IPersonApi.cs
TenureListener/Gateway/PersonApi.cs
TenureListener/UseCase/AddNewPersonToTenure.cs
TenureListener/UseCase/UpdatePersonDetailsOnTenure.cs

https://hackney.atlassian.net/browse/MTTL-1620
Added x-correlation-id request header to Api call

Added x-correlation-id request header to Api call

---

TenureListener.Tests/E2ETests/Fixtures/AccountApiFixture.cs
TenureListener.Tests/E2ETests/Fixtures/BaseApiFixture.cs
TenureListener.Tests/E2ETests/Steps/UpdateAccountDetailsOnTenureSteps.cs
TenureListener.Tests/E2ETests/Stories/UpdateAccountDetailsOnTenureTests.cs
TenureListener.Tests/UseCase/UpdateAccountDetailsOnTenureTests.cs
TenureListener/Domain/Account/AccountResponseObject.cs
TenureListener/Domain/Account/AccountTenure.cs
TenureListener/UseCase/UpdateAccountDetailsOnTenure.cs

https://hackney.atlassian.net/browse/MTTL-1741
Updates to take account of how the Accout Api actually works in practice.

Updates for Account Api workings

---

TenureListener.Tests/E2ETests/Fixtures/AccountApiFixture.cs
TenureListener/Domain/Account/AccountTenure.cs

https://hackney.atlassian.net/browse/MTTL-1741

Minor changes

---

TenureListener.Tests/E2ETests/Steps/UpdatePersonDetailsOnTenureSteps.cs
TenureListener/serverless.yml

Release changes to serverless.yml

Amend Account API Token Path

---

.circleci/config.yml

[Jira Ticket](https://hackney.atlassian.net/browse/MTTL-2172)
Add Nuget context to pipeline

add nuget context

---

.circleci/config.yml
TenureListener/serverless.yml

[JIRA ticket](https://hackney.atlassian.net/browse/MTTL-2389)
Removed deprecated --account flag

Removed deprecated --account flag

---

.circleci/config.yml
TenureListener.Tests/Dockerfile

https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?assignee=624c20c6a629c30068a81020&selectedIssue=MTTL-2956
Resolve SonarCloud Issues

SonarCloud Issue

---

TenureListener.Tests/TenureListener.Tests.csproj
TenureListener/TenureListener.csproj

Update Tenure shared nuget package

Tenure shared package update

---

.circleci/config.yml
TenureListener.Tests/Dockerfile
TenureListener.Tests/TenureListener.Tests.csproj
TenureListener/Dockerfile
TenureListener/Properties/launchSettings.json
TenureListener/SqsFunction.cs
TenureListener/TenureListener.csproj
TenureListener/aws-lambda-tools-defaults.json
TenureListener/build.cmd
TenureListener/build.sh
TenureListener/serverless.yml

[MTTL-3272](https://hackney.atlassian.net/browse/MTTL-3272)
Upgrade Tenure Listener to .net6

upgrade tenure listener to .net6

---

TenureListener/TenureListener.csproj

[HT20-586: Move Storage to Booking page](https://hackney.atlassian.net/browse/HT20-586)
[HT20-694: Add rent adjustment editor to booking page](https://hackney.atlassian.net/browse/HT20-694)
Update shared tenure package to 0.20.0
Add separate fields to the charges object to store temporary accommodation charges.

Update shared tenure package to 0.20.0

---

CODEOWNERS
TenureListener.Tests/Dockerfile
TenureListener/TenureListener.csproj

This is to upgrade the version of the Shared package for Tenure and keep it aligned with the API.

TS-1405: Upgrade shared package version

---

TenureListener/TenureListener.csproj

https://hackney.atlassian.net/browse/TS-1416
Updating shared package version to latest for tidiness.
PRs for package upgrades:
https://github.com/LBHackney-IT/tenure-shared/pull/31
https://github.com/LBHackney-IT/tenure-shared/pull/32

TS-1416: Keep Hackney.Shared.Tenure version up to date

---

.circleci/config.yml
Makefile
TenureListener.Tests/Dockerfile
TenureListener.Tests/MockApplicationFactory.cs
TenureListener.Tests/TenureListener.Tests.csproj
TenureListener/Dockerfile
TenureListener/Properties/launchSettings.json
TenureListener/TenureListener.csproj
TenureListener/aws-lambda-tools-defaults.json
TenureListener/build.cmd
TenureListener/build.sh
TenureListener/serverless.yml
docker-compose.yml

[HPT-611](https://hackney.atlassian.net/browse/HPT-611) Upgrade APIs to Dotnet 8
[HPT-611]: https://hackney.atlassian.net/browse/HPT-611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Upgrade API to Dotnet 8

---

.circleci/config.yml
Makefile
TenureListener.Tests/Dockerfile
TenureListener.Tests/MockApplicationFactory.cs
TenureListener.Tests/TenureListener.Tests.csproj
TenureListener/Dockerfile
TenureListener/Properties/launchSettings.json
TenureListener/TenureListener.csproj
TenureListener/aws-lambda-tools-defaults.json
TenureListener/build.cmd
TenureListener/build.sh
TenureListener/serverless.yml
docker-compose.yml

Release #73 - upgrade to dotnet 8

Upgrade to Dotnet 8
